# Generated by Django 4.0.4 on 2022-05-26 00:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convidados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Escreva seu nome, escreva sua história', max_length=100, verbose_name='Nome da Lenda')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='seu email')),
                ('opcao', models.CharField(choices=[('30', 'R$ 30,00 - Vou só comer'), ('50', 'R$ 50,00 - Vou encher a cara e comer')], max_length=50, verbose_name='opções')),
            ],
        ),
    ]
