# Generated by Django 4.0.4 on 2022-05-26 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='convidados',
            options={'verbose_name': 'Convidado', 'verbose_name_plural': 'Convidados'},
        ),
        migrations.AddField(
            model_name='convidados',
            name='telefone',
            field=models.CharField(max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
